package model

import "time"

// Analysis represents a complete market strategy analysis.
// It contains all reference data, input scores, configuration,
// and computed outputs.
type Analysis struct {
	// ID is a unique identifier for this analysis.
	ID string `json:"id"`

	// Name is a human-readable name for this analysis.
	Name string `json:"name"`

	// Description provides context about the analysis.
	Description string `json:"description,omitempty"`

	// Version tracks the analysis version for change management.
	Version string `json:"version,omitempty"`

	// CreatedAt is when the analysis was created.
	CreatedAt time.Time `json:"createdAt"`

	// UpdatedAt is when the analysis was last modified.
	UpdatedAt time.Time `json:"updatedAt"`

	// FocusVendorID is the primary vendor being analyzed (optional).
	// If set, gap analysis is computed from this vendor's perspective.
	FocusVendorID string `json:"focusVendorId,omitempty"`

	// Reference Data
	// These define the structure of the analysis.

	// Market defines the industry vertical and product categories.
	Market Market `json:"market"`

	// Segments defines the customer segments for analysis.
	Segments []Segment `json:"segments"`

	// Vendors lists all vendors being compared.
	Vendors []Vendor `json:"vendors"`

	// VendorProducts maps vendors to their product offerings.
	VendorProducts []VendorProduct `json:"vendorProducts,omitempty"`

	// Sources lists data sources used for scoring.
	Sources []DataSource `json:"sources"`

	// Configuration
	// These control how the analysis is computed.

	// Weights defines segment-specific capability importance.
	Weights []SegmentWeight `json:"weights"`

	// Normalizations defines how to convert raw scores.
	Normalizations []ScoreNormalization `json:"normalizations,omitempty"`

	// Input Data
	// These are the raw scores feeding the analysis.

	// Scores contains all capability scores for all vendors.
	Scores []CapabilityScore `json:"scores"`

	// Computed Outputs
	// These are generated by the engine.

	// Gaps contains computed capability gaps.
	Gaps []GapAnalysis `json:"gaps,omitempty"`

	// Readiness contains segment readiness scores per vendor.
	Readiness []ReadinessScore `json:"readiness,omitempty"`

	// Priorities contains the prioritized action list.
	Priorities []PriorityAction `json:"priorities,omitempty"`

	// Comparisons contains segment-level competitive comparisons.
	Comparisons []SegmentComparison `json:"comparisons,omitempty"`

	// Metadata
	// Additional tracking information.

	// ComputedAt is when the outputs were last computed.
	ComputedAt time.Time `json:"computedAt,omitempty"`

	// Notes provides additional context about the analysis.
	Notes string `json:"notes,omitempty"`

	// Tags allows categorization and filtering.
	Tags []string `json:"tags,omitempty"`
}

// AnalysisSummary provides a high-level overview of an analysis.
type AnalysisSummary struct {
	// ID is the analysis identifier.
	ID string `json:"id"`

	// Name is the analysis name.
	Name string `json:"name"`

	// Market is the market name.
	Market string `json:"market"`

	// VendorCount is the number of vendors analyzed.
	VendorCount int `json:"vendorCount"`

	// CapabilityCount is the number of capabilities measured.
	CapabilityCount int `json:"capabilityCount"`

	// SegmentCount is the number of segments analyzed.
	SegmentCount int `json:"segmentCount"`

	// UpdatedAt is when the analysis was last modified.
	UpdatedAt time.Time `json:"updatedAt"`

	// FocusVendor is the primary vendor name (if set).
	FocusVendor string `json:"focusVendor,omitempty"`

	// FocusVendorReadiness is the focus vendor's average readiness.
	FocusVendorReadiness map[string]float64 `json:"focusVendorReadiness,omitempty"`
}

// Summary generates a summary of the analysis.
func (a *Analysis) Summary() AnalysisSummary {
	summary := AnalysisSummary{
		ID:              a.ID,
		Name:            a.Name,
		Market:          a.Market.Name,
		VendorCount:     len(a.Vendors),
		SegmentCount:    len(a.Segments),
		UpdatedAt:       a.UpdatedAt,
		CapabilityCount: 0,
	}

	// Count capabilities across all categories
	for _, cat := range a.Market.Categories {
		summary.CapabilityCount += len(cat.Capabilities)
	}

	// Add focus vendor info if present
	if a.FocusVendorID != "" {
		for _, v := range a.Vendors {
			if v.ID == a.FocusVendorID {
				summary.FocusVendor = v.Name
				break
			}
		}

		// Add readiness scores for focus vendor
		summary.FocusVendorReadiness = make(map[string]float64)
		for _, r := range a.Readiness {
			if r.VendorID == a.FocusVendorID {
				// Find segment name
				for _, s := range a.Segments {
					if s.ID == r.SegmentID {
						summary.FocusVendorReadiness[s.Name] = r.Score
						break
					}
				}
			}
		}
	}

	return summary
}

// GetVendor returns a vendor by ID.
func (a *Analysis) GetVendor(id string) *Vendor {
	for i := range a.Vendors {
		if a.Vendors[i].ID == id {
			return &a.Vendors[i]
		}
	}
	return nil
}

// GetSegment returns a segment by ID.
func (a *Analysis) GetSegment(id string) *Segment {
	for i := range a.Segments {
		if a.Segments[i].ID == id {
			return &a.Segments[i]
		}
	}
	return nil
}

// GetCapability returns a capability by ID.
func (a *Analysis) GetCapability(id string) *Capability {
	for _, cat := range a.Market.Categories {
		for i := range cat.Capabilities {
			if cat.Capabilities[i].ID == id {
				return &cat.Capabilities[i]
			}
		}
	}
	return nil
}

// GetWeight returns the weight for a segment/capability pair.
func (a *Analysis) GetWeight(segmentID, capabilityID string) float64 {
	for _, w := range a.Weights {
		if w.SegmentID == segmentID && w.CapabilityID == capabilityID {
			return w.Weight
		}
	}
	return 0
}

// GetScore returns the score for a vendor/capability pair.
func (a *Analysis) GetScore(vendorID, capabilityID string) *CapabilityScore {
	for i := range a.Scores {
		if a.Scores[i].VendorID == vendorID && a.Scores[i].CapabilityID == capabilityID {
			return &a.Scores[i]
		}
	}
	return nil
}
